### ISSUE TITLE
Display number of packages from other package managers

### ISSUE THREAD

**Issue by laurentlbm** [grtcdr/macchina#46]
It would be interesting to show the number of global packages from:

- snap
- flatpak
- brew (macOS and Linux)
- npm
- cargo
- choco (Windows)
- scoop (Windows)
- others?

Important consideration: How do we avoid a performance hit?

**Comment by grtcdr** [comment]
Do you mean printing the packages of every installed package manager?

**Example:**
420 (pacman), 1 (snap)

**Comment by laurentlbm** [comment]
Yes, exactly. Though, to be honest, I see it as very low priority; I usually don't have many packages from sources other than pacman on Arch and dnf on Fedora. Nonetheless, the issue could stay open until others show more interest.

**Comment by grtcdr** [comment]
I totally agree, I for one, wouldn't benefit from this as I only have pacman installed and do not use any other package managers to keep disk usage as low as possible. 
But other users probably would like to see this implemented.

The only people who would take a performance hit from this those who do have multiple package managers installed, because Macchina only fetches your package information if the respective package manager is installed.

**Comment by grtcdr** [comment]
The mentioned PR provides the ability to display the number of packages from multiple package managers :)
